"""
report_gen.py
=============
PDF generation and WhatsApp share utilities for GenPredict NG.
Uses fpdf2 (pure Python, no GTK dependencies).
"""

import json
import urllib.parse
from datetime import datetime
from io import BytesIO
from fpdf import FPDF, XPos, YPos


# ═══════════════════════════════════════════════════════════
#  COLOUR PALETTE
# ═══════════════════════════════════════════════════════════
DARK_BG    = (15, 15, 26)
AMBER      = (245, 158, 11)
EMERALD    = (16, 185, 129)
RED        = (239, 68, 68)
ORANGE     = (249, 115, 22)
GREY       = (148, 163, 184)
WHITE      = (255, 255, 255)

RISK_COLORS = {
    'HEALTHY':   EMERALD,
    'MODERATE':  AMBER,
    'HIGH RISK': ORANGE,
    'CRITICAL':  RED,
}


def _risk_color(risk_level):
    return RISK_COLORS.get(risk_level, GREY)


# ═══════════════════════════════════════════════════════════
#  PDF REPORT CLASS
# ═══════════════════════════════════════════════════════════

class GenPredictPDF(FPDF):
    def __init__(self, generator, prediction, maintenance_records, logs):
        super().__init__()
        self.generator  = generator
        self.prediction = prediction
        self.maintenance = maintenance_records
        self.logs = logs
        self.set_margins(15, 15, 15)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Dark header bar
        self.set_fill_color(*DARK_BG)
        self.rect(0, 0, 210, 22, 'F')
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(*AMBER)
        self.set_y(6)
        self.cell(0, 10, 'GenPredict NG - Generator Health Report', align='C',
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_y(25)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*GREY)
        self.cell(0, 10,
                  f'Generated by GenPredict NG • {datetime.utcnow().strftime("%Y-%m-%d %H:%M")} UTC • Page {self.page_no()}',
                  align='C')

    def section_title(self, title):
        self.ln(4)
        self.set_font('Helvetica', 'B', 11)
        self.set_fill_color(240, 240, 245)
        self.set_text_color(*DARK_BG)
        self.cell(0, 8, f'  {title}', fill=True,
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(2)

    def kv_row(self, key, value, bold_value=False):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(80, 80, 80)
        self.cell(65, 7, key + ':', new_x=XPos.RIGHT, new_y=YPos.LAST)
        if bold_value:
            self.set_font('Helvetica', 'B', 10)
        self.set_text_color(0, 0, 0)
        # Handle em-dash/unicode in strings
        val_str = str(value).replace('\u2014', '-').replace('\u2013', '-')
        self.cell(0, 7, val_str, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def health_badge(self, score, risk_level):
        r, g, b = _risk_color(risk_level)
        # Score box
        self.set_fill_color(r, g, b)
        self.set_text_color(*WHITE)
        self.set_font('Helvetica', 'B', 28)
        self.cell(50, 20, f'{score:.0f}', fill=True, align='C',
                  new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.set_font('Helvetica', 'B', 14)
        self.set_fill_color(r, g, b)
        self.cell(60, 20, f'  {risk_level}', fill=True, align='L',
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def indicator_row(self, label, value, description, status):
        status_colors = {
            'good': EMERALD, 'warning': AMBER,
            'danger': ORANGE, 'critical': RED
        }
        r, g, b = status_colors.get(status, GREY)
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(0, 0, 0)
        self.cell(55, 7, label, new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.set_fill_color(r, g, b)
        self.set_text_color(*WHITE)
        self.set_font('Helvetica', 'B', 9)
        self.cell(22, 7, f'{value:.3f}', fill=True, align='C',
                  new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.set_text_color(60, 60, 60)
        self.set_font('Helvetica', '', 8)
        self.cell(0, 7, f'  {description}', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def recommendations_section(self, recs):
        priority_labels = {
            'critical': ('CRITICAL', RED),
            'high':     ('HIGH',     ORANGE),
            'medium':   ('MEDIUM',   AMBER),
            'low':      ('LOW',      EMERALD),
            'info':     ('INFO',     (59, 130, 246)),
        }
        for i, rec in enumerate(recs, 1):
            label, (r, g, b) = priority_labels.get(rec['priority'], ('INFO', GREY))
            self.set_fill_color(r, g, b)
            self.set_text_color(*WHITE)
            self.set_font('Helvetica', 'B', 8)
            self.cell(20, 6, label, fill=True, align='C',
                      new_x=XPos.RIGHT, new_y=YPos.LAST)
            self.set_text_color(0, 0, 0)
            self.set_font('Helvetica', 'B', 9)
            self.cell(0, 6, f"  * {rec['action']}",
                      new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(80, 80, 80)
            self.set_x(20)
            self.multi_cell(0, 5, rec['reason'],
                            new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.ln(1)


def generate_pdf_report(generator, prediction, maintenance_records, logs):
    """
    Generate a PDF maintenance report byte stream.
    Returns: BytesIO object ready to send as response.
    """
    recs = json.loads(prediction.recommendations) if prediction.recommendations else []

    pdf = GenPredictPDF(generator, prediction, maintenance_records, logs)
    pdf.add_page()

    # ── Cover Info ─────────────────────────────────────────
    pdf.section_title('Generator Information')
    pdf.kv_row('Generator Name',  generator.name)
    pdf.kv_row('Make / Model',    f"{generator.make or '-'} / {generator.model or '-'}")
    pdf.kv_row('KVA Rating',      f"{generator.kva_rating} KVA")
    pdf.kv_row('Fuel Type',       generator.fuel_type or '-')
    pdf.kv_row('Year of Purchase', generator.purchase_year or '-')
    pdf.kv_row('Age (Years)',     f"{generator.age_years} year(s)")
    pdf.kv_row('Report Date',     datetime.utcnow().strftime('%d %B %Y'))

    # ── Health Score ───────────────────────────────────────
    pdf.section_title('Composite Health Score')
    pdf.health_badge(prediction.health_score, prediction.risk_level)
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6,
             f'Based on {prediction.logs_used} daily log entries. '
             f'Days to next recommended service: {prediction.days_to_service}',
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Layer 2: Indicators ────────────────────────────────
    pdf.section_title('Processing Layer — Health Indicators')

    def fer_status(v):
        if v <= 1.1: return 'good'
        if v <= 1.25: return 'warning'
        if v <= 1.5: return 'danger'
        return 'critical'

    def mos_status(v):
        if v < 0.7: return 'good'
        if v < 1.0: return 'warning'
        if v < 1.5: return 'danger'
        return 'critical'

    def aals_status(v):
        if v < 0.35: return 'good'
        if v < 0.60: return 'warning'
        if v < 0.85: return 'danger'
        return 'critical'

    def ffr_status(v):
        if v == 0: return 'good'
        if v < 0.1: return 'good'
        if v < 0.3: return 'warning'
        if v < 0.5: return 'danger'
        return 'critical'

    uii_s = 'good' if prediction.uii < 0.7 else ('warning' if prediction.uii < 0.85 else 'danger')
    pdf.indicator_row('Usage Intensity Index (UII)',
                      prediction.uii, f'{prediction.uii*100:.1f}% of max daily capacity', uii_s)
    pdf.indicator_row('Fuel Efficiency Ratio (FER)',
                      prediction.fer, f'{int((prediction.fer-1)*100):+d}% vs expected consumption', fer_status(prediction.fer))
    pdf.indicator_row('Maintenance Overdue Score (MOS)',
                      prediction.mos, f'{prediction.mos:.2f}x recommended interval', mos_status(prediction.mos))
    pdf.indicator_row('Age-Adjusted Load Stress (AALS)',
                      prediction.aals, 'Combined age, load, and usage stress', aals_status(prediction.aals))
    pdf.indicator_row('Fault Frequency Rate (FFR)',
                      prediction.ffr, f'{prediction.ffr:.3f} faults per day (last 30 days)', ffr_status(prediction.ffr))

    # ── Recommendations ────────────────────────────────────
    pdf.section_title('Prioritised Maintenance Recommendations')
    pdf.recommendations_section(recs)

    # ── Maintenance History ────────────────────────────────
    if maintenance_records:
        pdf.section_title('Maintenance History (Last 5 Records)')
        for rec in maintenance_records[:5]:
            pdf.set_font('Helvetica', 'B', 9)
            pdf.set_text_color(0, 0, 0)
            date_str = rec.maintenance_date.strftime('%d %b %Y') if rec.maintenance_date else '-'
            type_str = (rec.maintenance_type or "Service").replace('\u2014', '-')
            pdf.cell(0, 6, f'{date_str}  -  {type_str}',
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            if rec.description:
                pdf.set_font('Helvetica', '', 8)
                pdf.set_text_color(80, 80, 80)
                pdf.set_x(20)
                desc_str = rec.description.replace('\u2014', '-').replace('\u2013', '-')
                pdf.multi_cell(0, 5, desc_str,
                               new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            if rec.cost_naira:
                pdf.set_font('Helvetica', 'I', 8)
                pdf.set_x(20)
                pdf.cell(0, 5, f'Cost: NGN {rec.cost_naira:,.0f}',
                         new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(1)

    # ── Recent Logs Table ──────────────────────────────────
    if logs:
        pdf.section_title('Recent Daily Logs (Last 7 Days)')
        # Table header
        pdf.set_fill_color(*DARK_BG)
        pdf.set_text_color(*WHITE)
        pdf.set_font('Helvetica', 'B', 8)
        col_w = [28, 22, 20, 22, 18, 22, 48]
        headers = ['Date', 'Usage Hrs', 'Load %', 'Fuel (L)', 'Faults', 'NEPA Hrs', 'Notes']
        for h, w in zip(headers, col_w):
            pdf.cell(w, 7, h, fill=True, align='C', border=1, new_x=XPos.RIGHT, new_y=YPos.LAST)
        pdf.ln()
        # Rows
        for i, log in enumerate(logs[:7]):
            fill = (i % 2 == 0)
            pdf.set_fill_color(248, 248, 252) if fill else pdf.set_fill_color(*WHITE)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font('Helvetica', '', 8)
            row = [
                log.log_date.strftime('%d %b %Y') if log.log_date else '—',
                f'{log.usage_hours:.1f}',
                f'{log.load_level}%',
                f'{log.fuel_consumed:.1f}',
                str(log.fault_count),
                f'{log.nepa_outage_hours:.1f}',
                (log.notes or '—')[:30],
            ]
            for val, w in zip(row, col_w):
                pdf.cell(w, 6, val, fill=fill, border=1,
                         align='C', new_x=XPos.RIGHT, new_y=YPos.LAST)
            pdf.ln()

    # Output
    buf = BytesIO()
    buf.write(pdf.output())
    buf.seek(0)
    return buf


# ═══════════════════════════════════════════════════════════
#  WHATSAPP SHARE LINK
# ═══════════════════════════════════════════════════════════

def generate_whatsapp_link(generator, prediction):
    """Generate a pre-filled WhatsApp message link for sharing the report."""
    risk_emoji = {
        'HEALTHY':   '🟢',
        'MODERATE':  '🟡',
        'HIGH RISK': '🟠',
        'CRITICAL':  '🔴',
    }.get(prediction.risk_level, '⚪')

    recs = json.loads(prediction.recommendations) if prediction.recommendations else []
    top_action = recs[0]['action'] if recs else 'Keep monitoring.'

    message = (
        f"🔧 *GenPredict NG — Generator Health Report*\n\n"
        f"*Generator:* {generator.name} ({generator.kva_rating} KVA {generator.fuel_type})\n"
        f"*Make/Model:* {generator.make or '—'} / {generator.model or '—'}\n"
        f"*Age:* {generator.age_years} year(s)\n\n"
        f"━━━━━━━━━━━━━━━━━━━━━\n"
        f"*Health Score:* {prediction.health_score:.0f}/100\n"
        f"*Risk Level:* {risk_emoji} {prediction.risk_level}\n"
        f"*Days to Service:* {prediction.days_to_service}\n\n"
        f"*Top Recommendation:*\n{top_action}\n\n"
        f"━━━━━━━━━━━━━━━━━━━━━\n"
        f"*Indicators:*\n"
        f"• Usage Intensity: {prediction.uii*100:.1f}% of daily max\n"
        f"• Fuel Efficiency: {int((prediction.fer-1)*100):+d}% vs expected\n"
        f"• Maintenance Due: {prediction.mos:.2f}x interval\n"
        f"• Load Stress: {prediction.aals:.3f}\n"
        f"• Fault Rate: {prediction.ffr:.3f}/day\n\n"
        f"_Report generated by GenPredict NG_"
    )

    encoded = urllib.parse.quote(message)
    return f"https://wa.me/?text={encoded}"
